version: "3"
services:
  app:
    build: .
    volumes:
      - ./web:/var/www/html/vuesplash
    ports:
      - 8081:8081
      - 3000:3000
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
